<?php
/**
 * The template for displaying the footer on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/footer.scss.
 * The "Footer Columns" generated by PHP can be configured in functions.php.
 *
 * Contains the footer of the site as well as WP's required code and the closing body and HTML tags.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Big_Day_Design
 * @since 1.0.0
 */
?>

<!--Start Footer-->
    <div class="bg-purple-gradient py-4"></div>

    <div class="bg-no-repeat bg-scroll bg-cover bg-blue-gradient">
        <div class="mx-4 md:mx-10 lg:max-w-6xl lg:mx-auto py-10">
            <div class="grid grid-cols-12 gap-4">
                <div class="col-span-12 text-center">
                    <h6 class="uppercase text-md font-bold text-black">Your website is officially out of your hands</h6>
                    <a href="/contact" class="underline"> <p class="text-md font-bold  text-black">Start the Process</p></a>
                </div>

                <div class="col-span-12 text-center">
                    <i class="fa-brands fa-instagram text-3xl"></i>
                </div>

                <div class="col-span-12 text-center">
                    <h6 class="text-sm font-bold text-black"><a href="/privacy-policy">Privacy Policy</a></h6>
                </div>
            </div>
        </div>
    </div>
<!--End Footer-->


<!--Wordpress Requires This-->
<?php wp_footer(); ?>

</body>
</html>

